export const PERMISSIONS_NAME = {
  CAN_ADD_NEW_ROLE_TO_AN_USER: "CAN_ADD_NEW_ROLE_TO_AN_USER",
  CAN_REMOVE_A_ROLE_FROM_AN_USER: "CAN_REMOVE_A_ROLE_FROM_AN_USER",

  CAN_CREATE_NEW_ROLES: "CAN_CREATE_NEW_ROLES",
  CAN_DELETE_ROLES: "CAN_DELETE_ROLES",

  CAN_CREATE_NEW_EXERCISES: "CAN_CREATE_NEW_EXERCISES",
  CAN_DELETE_EXERCISES: "CAN_DELETE_EXERCISES",
};
