import { PERMISSIONS_NAME } from "../enums/permissions-name";

export const USER_ROLE_PERMISSIONS = {
  [PERMISSIONS_NAME.CAN_ADD_NEW_ROLE_TO_AN_USER]: false,
  [PERMISSIONS_NAME.CAN_REMOVE_A_ROLE_FROM_AN_USER]: false,
  [PERMISSIONS_NAME.CAN_CREATE_NEW_ROLES]: false,
  [PERMISSIONS_NAME.CAN_DELETE_ROLES]: false,
  [PERMISSIONS_NAME.CAN_CREATE_NEW_EXERCISES]: false,
  [PERMISSIONS_NAME.CAN_DELETE_EXERCISES]: false,
};

export const ADMIN_ROLE_PERMISSIONS = {
  [PERMISSIONS_NAME.CAN_ADD_NEW_ROLE_TO_AN_USER]: true,
  [PERMISSIONS_NAME.CAN_REMOVE_A_ROLE_FROM_AN_USER]: true,
  [PERMISSIONS_NAME.CAN_CREATE_NEW_ROLES]: true,
  [PERMISSIONS_NAME.CAN_DELETE_ROLES]: true,
  [PERMISSIONS_NAME.CAN_CREATE_NEW_EXERCISES]: true,
  [PERMISSIONS_NAME.CAN_DELETE_EXERCISES]: true,
};

export const ADMIN_EMAILS = ["bazilucm@gmail.com"];
