### Register user: /api/auth/register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json


{
  "email": "bazilucm@gmail.com",
  "userName":"marian b",
  "password":"123456"
}


###  Login user: /api/auth/login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "bazilucm@gmail.com",
  "password":"123456"
}


###  Logout user: /api/auth/logout
POST {{baseUrl}}/api/auth/logout

###  Verify OTP code /api/auth/verify-otp
POST {{baseUrl}}/api/auth/verify-otp
Content-Type: application/json

{
  "otpCode":"802182",
  "email":"bazilucm@gmail.com"
}


###  Resend OTP code /api/auth/resend-otp
POST {{baseUrl}}/api/auth/resend-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF3cWM3Zjh5M2NhM2FveiIsImZpcnN0TmFtZSI6Imxxd3FjN2Y4eTNjYTNhb3oiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiZDc0YTlkOGRiNThlZTRmZWI4MDdkMTA4YTU1MThlMjc4ODkwMjllZDU3ZjM3ZDExZTQ5YTAxMjc5YThkNzMwMjk4N2E1ZGY2OTA4NjVlMzY1OTNiMGUzZGEwYWY3YTJiMGQ0OTJlOTQzODM2Y2JiYmUyMjE4Njg4ODdhODliMjQiLCJpYXQiOjE3MDQyNjI0Mjd9.5JMNYH6HGX5SbcQUfNOnQR8GVOiWzULhG3BRYh0ActY

{
  "email":"bazilucm@gmail.com"
}


###  Forgot password code /api/auth/forgot-password
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
  "email":"bazilucm@gmail.com"
}


###  Reset password /api/auth/reset-password
POST {{baseUrl}}/api/auth/reset-password
Content-Type: application/json

{
  "email":"bazilucm@gmail.com",
  "resetToken":"290945",
  "password":"1234567",
  "confirmPassword":"1234567"
}



###  Reset password /api/auth/reset-password
POST {{baseUrl}}/api/auth/refresh-token

###  Cleanup unverified OTP user accounts (isVerifiedOTp -> false)
POST {{baseUrl}}/api/auth/cleanup-otp-users
