### Get current user info : /api/user/currentUser
GET  {{baseUrl}}/api/user/currentUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get current  user info : /api/user/currentUser
PATCH  {{baseUrl}}/api/user/lqzjyncxxrjbmlic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

{
  "avatarImage":"https://avatar.jpg",
  "phoneNumber": "0757357597",
  "sex":"Male",
  "nationality":"Romania",
  "birthDate":"1998-07-29T21:00:00.000Z"
}
