### Get current user info : /api/user/currentUser
GET  {{baseUrl}}/api/user/currentUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get current  user info : /api/user/currentUser
PATCH  {{baseUrl}}/api/user/lwc6rbym0unoehe7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHdjNnJieW0wdW5vZWhlNyIsInVzZXJOYW1lIjoiYmF6bHVjbWkiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTYwOTc2MjksImV4cCI6MTcxNjA5NzgwOX0.OslJpYjaKQccH4k25DZbht8-OhQO8dxgCvz73sne1zA

{
  "gender":"Male",
  "goal":["Learn new things", "Gain knowledge"],
  "weight":100,
  "height":120,
  "activityLevel":"Intermediate",
  "isOnboarded":true
}
