### Get all the exercises /api/exercises?query
GET  http://localhost:3000/api/exercises?limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHI0bzN1MHRvNWNjb3NsZSIsImZpcnN0TmFtZSI6Ik1hcmlhbiIsImxhc3ROYW1lIjoiQmF6aWx1YyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcwNDcwMjk0NSwiZXhwIjoxNzA0NzM4OTQ1fQ.FsB6H0FWBxZNIQa9kNEBpdIRpSVslvZsYYB0GIQMarU


### Search the exercises by name /api/exercises/search?query
GET  http://localhost:3000/api/exercises/search?name=squat&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get the exercise by id /api/exercises/:exerciseId
GET  http://localhost:3000/api/exercises/0436
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get the exercises by muscle target  /api/exercises/target?target=abductors&limit=10&offset=0
GET  http://localhost:3000/api/exercises/target?target=tricepss&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get the exercises by equipment type  /api/exercises/equipment?equipmentType=&limit=10&offset=0
GET  http://localhost:3000/api/exercises/equipment?equipmentType=rope&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY
### Get the muscle target list  /api/exercises/muscle-target-list
GET  http://localhost:3000/api/exercises/muscle-target-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY
### Get the muscle equipment list  /api/exercises/equipment-list
GET  http://localhost:3000/api/exercises/equipment-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY
### Get the body part list  /api/exercises/body-part-list
GET  http://localhost:3000/api/exercises/body-part-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY

### Get the exercises by body part /api/exercises/body-part?bodyPart=chest&limit=10&offset=0
GET  http://localhost:3000/api/exercises/body-part?bodyPart=chest&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF6anluY3h4cmpibWxpYyIsImZpcnN0TmFtZSI6Imxxemp5bmN4eHJqYm1saWMiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNGM1Mjg4OThkZDQyYWFlMWI4ZTdjNmI5ODkwMzRkYjc2Y2IwNmQyODYxNTI3ODkyNzNhYTgxZjkwNDVhMDFlNDIzN2E4ODI3ZDAyMDJiMzA3MDJhMzE2N2Q0OTBkMWI1NTA3YjgzYTdhYzZlY2JiODk1MWExYWE0Mjg3NDI4NTkiLCJpYXQiOjE3MDQzOTM2NTksImV4cCI6MTcwNDQyOTY1OX0.hWR4shAUEIAh2nlEF6yVKdPlhinUAjIneMzPXZCQqsY