### Get all the exercises /api/exercises?query
GET  http://localhost:3000/api/exercises?limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF3cWM3Zjh5M2NhM2FveiIsImZpcnN0TmFtZSI6Imxxd3FjN2Y4eTNjYTNhb3oiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiNzgyNWVjYWViY2Q1NTMwYTE5NDY2MjNiYTRjZTk1Yzg4MDdlMjBjM2IwNjFlOTVhYjBkMzZkMGE4ZGNiOTgzYzFhMTY2MDU3OGYzNjk3Njg2ODM2NmE5MWU0MWM3ZDM1ZjMzNjk2MGE1ZGFmMzkwYjAyOWY2MTM2NTAzM2Y4YTYiLCJpYXQiOjE3MDQyMjM0Mzd9.B90JOVFCxz50YW4O60Ir6RGoO_jeYGl7DXkacaR-WZI


### Search the exercises by name /api/exercises/search?query
GET  http://localhost:3000/api/exercises/search?name=squat&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8


### Get the exercise by id /api/exercises/:exerciseId
GET  http://localhost:3000/api/exercises/0436
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8


### Get the exercises by muscle target  /api/exercises/target?target=abductors&limit=10&offset=0
GET  http://localhost:3000/api/exercises/target?target=tricepss&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8


### Get the exercises by equipment type  /api/exercises/equipment?equipmentType=&limit=10&offset=0
GET  http://localhost:3000/api/exercises/equipment?equipmentType=rope&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8

### Get the muscle target list  /api/exercises/muscle-target-list
GET  http://localhost:3000/api/exercises/muscle-target-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8

### Get the muscle equipment list  /api/exercises/equipment-list
GET  http://localhost:3000/api/exercises/equipment-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8

### Get the body part list  /api/exercises/body-part-list
GET  http://localhost:3000/api/exercises/body-part-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8


### Get the exercises by body part /api/exercises/body-part?bodyPart=chest&limit=10&offset=0
GET  http://localhost:3000/api/exercises/body-part?bodyPart=chest&limit=10&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imxxc2RydTFoZHlvdHpydGEiLCJmaXJzdE5hbWUiOiJscXNkcnUxaGR5b3R6cnRhIiwibGFzdE5hbWUiOiJCYXppbHVjIiwiZW1haWwiOiJCYXppbHVjIiwiaWF0IjoxNzA0MTE1NDgxLCJleHAiOjE3MDQxNTE0ODF9.ZMcCj9QfL7ICWqOq88ezfYpfkeVkh5-PYKxFCmuads8
