### Get current user info : /api/user/currentUser
GET  http://localhost:3000/api/user/currentUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhemlsdWNtQGdtYWlsLmNvbSIsImlkIjoibHF3cWM3Zjh5M2NhM2FveiIsImZpcnN0TmFtZSI6Imxxd3FjN2Y4eTNjYTNhb3oiLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJvdHBDb2RlIjoiOWY0NTFlZTIxMzI5Mzc0NzhhNDRjZWI5MTc5NjJkYjkyN2FlZTRkOGQ1MDE0YjNhNDJmMjE4MDU4ZWUzMzM4MTA5OTJmOTBkY2RhZGJlZDQwYTliNDdiNTAwYjVkOWMwZThmOGRjN2I2MWZjOTljNTQwZGJhZDJjNjBiOWFmNTkiLCJpYXQiOjE3MDQyNzA3ODMsImV4cCI6MTcwNDMwNjc4M30.dNec3-iKXNSdOFH-Uc3MJqSRl8JFqIUhmyL63Xt5FJk

### Get current  user info : /api/user/currentUser
PATCH  http://localhost:3000/api/user/lqs9eejegvgf1hp3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImxxczllZWplZ3ZnZjFocDMiLCJmaXJzdE5hbWUiOiJNYXJpYW4iLCJsYXN0TmFtZSI6IkJhemlsdWMiLCJlbWFpbCI6IkJhemlsdWMiLCJpYXQiOjE3MDM5NTI2MjksImV4cCI6MTcwMzk4ODYyOX0.wj05dOz37EakdlTzQVO4dw81BkrdelE9HplxoQukRck

{
  "avatarImage":"https://avatar.jpg",
  "phoneNumber": "0757357597",
  "sex":"Male",
  "nationality":"Romania",
  "birthDate":"1998-07-29T21:00:00.000Z"
}
