const REGISTER_MEMBERSHIP_CARD = "/";
const REGISTER_DAILY_GYM_VISIT = "/visit";
const VERIFY_DAILY_GYM_VISIT = "/visit";
const GET_ALL_GYM_VISITS = "/visits";

export const MEMBERSHIP_CARD_ROUTES = {
  REGISTER_MEMBERSHIP_CARD,
  REGISTER_DAILY_GYM_VISIT,
  VERIFY_DAILY_GYM_VISIT,
  GET_ALL_GYM_VISITS,
};
